/**
 * events.js — bitcircus101 event renderer
 * Loads events from events-data.json (generated by CI),
 * falls back to ICS fetch from Nextcloud.
 */
(function () {
  "use strict";

  var JSON_URL = "events-data.json";
  var ICS_URL =
    "https://nc.6bm.de/remote.php/dav/public-calendars/DCaFSYECrcTJRJjC?export";
  var CALENDAR_URL =
    "https://nc.6bm.de/apps/calendar/p/DCaFSYECrcTJRJjC";
  var MONTHS = [
    "JAN", "FEB", "M\u00c4R", "APR", "MAI", "JUN",
    "JUL", "AUG", "SEP", "OKT", "NOV", "DEZ",
  ];
  var MONTHS_FULL = [
    "JANUAR", "FEBRUAR", "M\u00c4RZ", "APRIL", "MAI", "JUNI",
    "JULI", "AUGUST", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DEZEMBER",
  ];
  var DAYS = ["SO", "MO", "DI", "MI", "DO", "FR", "SA"];

  // State — shareable via the URL query (?tags=…&nur=bc&q=…). The hash stays
  // reserved for event anchors (#ev-…), so permalinks and filters compose.
  var PARAM = { TAGS: "tags", ONLY: "nur", Q: "q" };
  var state = { tags: [], onlyBitcircus: false, q: "" };
  var allFutureSorted = [];
  var feeds = null; // feeds manifest from events-data.json; null on old JSON / ICS fallback
  var eventsContainer = null;
  var filterBar = null;
  var eventsToolbar = null;
  var feedDefaults = null; // snapshot of the subscribe buttons' shipped hrefs

  function pad(n) { return n < 10 ? "0" + n : "" + n; }

  function esc(s) {
    return s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  // Bare-domain URLs (e.g. "bitcircus101.de") would render as a relative href
  // and 404. Prepend https:// when neither a scheme nor a root-relative path is
  // present. Mirrors the sync-side normalization in sync-events.mjs (5ee7f07).
  function httpUrl(u) {
    if (!u) return u;
    if (u.charAt(0) === "/") return u;
    // Only http(s)://… passes through unchanged. Other scheme://-URLs (ftp:, …)
    // and opaque schemes with no "//" (javascript:, data:, mailto:) both fall to
    // the https:// prepend below, which defuses any executable-href payload.
    var scheme = /^([a-z][\w+.-]*):\/\//i.exec(u);
    if (scheme && /^https?$/i.test(scheme[1])) return u;
    return "https://" + u;
  }

  function isBitcircusEvent(e) {
    return !e.source || e.source === "bitcircus101";
  }

  // ── URL state ─────────────────────────────────────────────────────────────

  function parseState() {
    var params = new URLSearchParams(window.location.search);
    var raw = (params.get(PARAM.TAGS) || "").split(",");
    state.tags = [];
    for (var i = 0; i < raw.length; i++) {
      var t = raw[i].trim();
      if (!t) continue;
      if (t.charAt(0) !== "#") t = "#" + t;
      if (state.tags.indexOf(t) === -1) state.tags.push(t);
    }
    state.onlyBitcircus = params.get(PARAM.ONLY) === "bc";
    state.q = (params.get(PARAM.Q) || "").trim();
  }

  // Fixed key order so identical views always serialize to one URL string.
  function serializeState() {
    var parts = [];
    if (state.tags.length) {
      parts.push(PARAM.TAGS + "=" + state.tags.map(function (t) {
        return encodeURIComponent(t.replace(/^#/, ""));
      }).join(","));
    }
    if (state.onlyBitcircus) parts.push(PARAM.ONLY + "=bc");
    if (state.q) parts.push(PARAM.Q + "=" + encodeURIComponent(state.q));
    return parts.length ? "?" + parts.join("&") : "";
  }

  var lastUrl = null;
  function syncUrl() {
    var url = window.location.pathname + serializeState() + window.location.hash;
    if (url === lastUrl) return; // Safari throttles replaceState (~100 calls/30s)
    lastUrl = url;
    window.history.replaceState(null, "", url);
  }

  // ── Search & filtering ───────────────────────────────────────────────────

  // Folded on BOTH sides so "lötkolben" and "loetkolben" hit the same events.
  function foldText(s) {
    return (s || "").toLowerCase()
      .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
      .replace(/\s+/g, " ");
  }

  function haystack(e) {
    if (!e.__hay) {
      e.__hay = foldText(
        e.title + " " + (e.subtitle || "") + " " + (e.description || "") + " " +
        (e.location || "") + " " + (e.tags || []).join(" ")
      );
    }
    return e.__hay;
  }

  function searchTokens() {
    return state.q ? foldText(state.q).split(" ").filter(Boolean) : [];
  }

  function matchesTags(e) {
    if (!state.tags.length) return true;
    return state.tags.some(function (f) { return (e.tags || []).indexOf(f) > -1; });
  }

  function matchesSearch(e, tokens) {
    for (var i = 0; i < tokens.length; i++) {
      if (haystack(e).indexOf(tokens[i]) === -1) return false;
    }
    return true;
  }

  // Source toggle applied, no cap — the chip source and the count denominator.
  function pool() {
    return state.onlyBitcircus
      ? allFutureSorted.filter(isBitcircusEvent)
      : allFutureSorted;
  }

  // Filter BEFORE the 30-cap so tags/search can reach events 31–40 of the
  // loaded window (the old order capped first and made them unreachable).
  function visibleEvents() {
    var tokens = searchTokens();
    return pool().filter(function (e) {
      return matchesTags(e) && matchesSearch(e, tokens);
    }).slice(0, 30);
  }

  // Tags in the URL that no loaded event carries (event passed, typo, …).
  function unknownTags() {
    var known = {};
    pool().forEach(function (e) {
      (e.tags || []).forEach(function (t) { known[t] = true; });
    });
    return state.tags.filter(function (t) { return !known[t]; });
  }

  // DOM removal only — state survives (the old version also cleared the active
  // filters here, which silently wiped tag filters on every source toggle).
  function removeFilterBar() {
    if (filterBar && filterBar.parentNode) {
      filterBar.parentNode.removeChild(filterBar);
    }
    filterBar = null;
  }

  // Mirror `state` into every control — checkbox, search input, chips, resets.
  function applyStateToControls() {
    var cb = document.getElementById("events-only-bitcircus");
    if (cb) cb.checked = state.onlyBitcircus;
    var input = document.getElementById("events-search");
    if (input && input.value !== state.q && document.activeElement !== input) {
      input.value = state.q;
    }
    var searchClear = document.querySelector(".events-search__clear");
    if (searchClear) searchClear.hidden = !state.q;
    if (filterBar) {
      filterBar.querySelectorAll(".events-filter__tag").forEach(function (b) {
        var on = state.tags.indexOf(b.getAttribute("data-tag")) > -1;
        b.classList.toggle("active", on);
        b.setAttribute("aria-pressed", on ? "true" : "false");
      });
      var clearBtn = filterBar.querySelector(".events-filter__clear");
      if (clearBtn) clearBtn.hidden = !state.tags.length && !state.q;
    }
  }

  // Single entry point after any state change; every handler ends here.
  function refresh(opts) {
    opts = opts || {};
    if (opts.rebuildChips) {
      removeFilterBar();
      buildChips();
    }
    applyStateToControls();
    renderFilteredCards();
    syncUrl();
    updateFeedScope();
  }

  function ensureEventsToolbar(insertBeforeNode) {
    if (eventsToolbar && eventsToolbar.parentNode) return;
    var parent = insertBeforeNode.parentNode;
    eventsToolbar = document.createElement("div");
    eventsToolbar.className = "events-toolbar";
    // Built by JS on purpose: the toolbar only exists when events rendered, so
    // a dead control never shows when JS or the data fails.
    eventsToolbar.innerHTML =
      '<div class="events-toolbar__row">' +
      '<label class="events-toolbar__label" for="events-only-bitcircus">' +
      '<input type="checkbox" id="events-only-bitcircus" class="events-toolbar__checkbox" />' +
      "<span>Nur Events im bitcircus101 anzeigen</span></label>" +
      "</div>" +
      '<div class="events-toolbar__row events-search">' +
      '<label class="events-search__label" for="events-search">suche:</label>' +
      '<input type="search" id="events-search" class="events-search__input" ' +
      'placeholder="titel, ort, schlagwort \u2026" autocomplete="off" />' +
      '<button type="button" class="events-search__clear" hidden aria-label="Suche l\u00f6schen">\u00d7</button>' +
      '<span class="events-search__count"></span>' +
      "</div>";
    parent.insertBefore(eventsToolbar, insertBeforeNode);

    document.getElementById("events-only-bitcircus").addEventListener(
      "change",
      function () {
        state.onlyBitcircus = this.checked;
        refresh({ rebuildChips: true }); // pool changed \u2192 chip set changes
      }
    );

    // One debounce for render AND URL \u2014 also caps replaceState frequency.
    var searchInput = document.getElementById("events-search");
    var searchTimer = null;
    searchInput.addEventListener("input", function () {
      var value = this.value;
      if (searchTimer) clearTimeout(searchTimer);
      searchTimer = setTimeout(function () {
        state.q = value.trim();
        refresh();
      }, 150);
    });
    eventsToolbar.querySelector(".events-search__clear").addEventListener(
      "click",
      function () {
        state.q = "";
        refresh();
      }
    );
  }

  // Chip source is pool() (pre-cap, post-toggle): stable while typing, changes
  // only on data load or source toggle \u2014 never on a chip click or keystroke.
  function buildChips() {
    var tagSet = {};
    pool().forEach(function (e) {
      (e.tags || []).forEach(function (t) { tagSet[t] = true; });
    });
    var allTags = Object.keys(tagSet).sort();
    if (allTags.length) buildFilterBar(allTags, eventsContainer);
  }

  // ── Card Renderer ─────────────────────────────────────────────────────────

  function renderCards(events, el) {
    eventsContainer = el;
    var now = new Date();
    now.setHours(0, 0, 0, 0);

    allFutureSorted = events
      .filter(function (e) {
        return new Date(e.date + "T23:59:59") >= now;
      })
      .sort(function (a, b) {
        // Date then time, so same-day events run chronologically (all-day first).
        return (a.date + (a.time || "")).localeCompare(b.date + (b.time || ""));
      });

    if (!allFutureSorted.length) {
      if (eventsToolbar && eventsToolbar.parentNode) {
        eventsToolbar.parentNode.removeChild(eventsToolbar);
        eventsToolbar = null;
      }
      removeFilterBar();
      el.innerHTML =
        '<p class="events-empty">Keine kommenden Termine gefunden.</p>' +
        '<p><a href="' + CALENDAR_URL + '" target="_blank" rel="noopener noreferrer">' +
        "Kalender \u00f6ffnen \u2197</a></p>";
      el.removeAttribute("aria-busy");
      return;
    }

    ensureEventsToolbar(el);
    refresh({ rebuildChips: true });

    // Anchor-wins: a permalink must always land. If the #ev-\u2026 target got
    // filtered away by URL state, drop the filters once and re-render \u2014 the
    // scroll happens in renderFilteredCards.
    var h = window.location.hash;
    if (h && h.indexOf("#ev-") === 0 && !document.getElementById(h.slice(1)) &&
        (state.tags.length || state.q || state.onlyBitcircus)) {
      state.tags = [];
      state.q = "";
      state.onlyBitcircus = false;
      refresh({ rebuildChips: true });
    }
  }

  function buildFilterBar(tags, el) {
    if (!tags.length) return;

    filterBar = document.createElement("div");
    filterBar.className = "events-filter";
    filterBar.setAttribute("role", "group");
    filterBar.setAttribute("aria-label", "Termine nach Schlagwort filtern");

    var html = '<span class="events-filter__label" aria-hidden="true">filter:</span>';
    tags.forEach(function (t) {
      html += '<button type="button" class="events-filter__tag" data-tag="' +
        esc(t) + '" aria-pressed="false">' + esc(t) + "</button>";
    });
    html += '<button type="button" class="events-filter__clear" hidden aria-label="Filter zur\u00fccksetzen">' +
      "\u00d7 reset</button>";
    filterBar.innerHTML = html;

    el.parentNode.insertBefore(filterBar, el);

    var clearBtn = filterBar.querySelector(".events-filter__clear");
    filterBar.querySelectorAll(".events-filter__tag").forEach(function (btn) {
      btn.addEventListener("click", function () {
        var tag = btn.getAttribute("data-tag");
        var idx = state.tags.indexOf(tag);
        if (idx > -1) state.tags.splice(idx, 1);
        else state.tags.push(tag);
        refresh();
      });
    });

    // Reset clears tags AND search (the search field has its own × for q only).
    clearBtn.addEventListener("click", function () {
      state.tags = [];
      state.q = "";
      refresh();
    });
  }

  function updateCount(shown) {
    var elC = document.querySelector(".events-search__count");
    if (!elC) return;
    // Only shown while a filter or search narrows the list \u2014 silent otherwise.
    elC.textContent = (state.q || state.tags.length)
      ? shown + " / " + pool().length + " termine"
      : "";
  }

  function renderFilteredCards() {
    var el = eventsContainer;
    var filtered = visibleEvents();
    updateCount(filtered.length);

    if (!filtered.length) {
      var unknown = unknownTags();
      var msg;
      if (unknown.length && !state.q) {
        msg = "Unbekanntes Schlagwort: " + esc(unknown.join(", ")) +
          " \u2014 vielleicht ist der Termin schon vorbei.";
      } else if (state.q && state.tags.length) {
        msg = "Keine Treffer f\u00fcr Filter + Suche.";
      } else if (state.q) {
        msg = "Keine Treffer f\u00fcr \u201e" + esc(state.q) + "\u201c.";
      } else if (state.onlyBitcircus && !state.tags.length) {
        msg = "Keine bevorstehenden Termine nur im bitcircus101-Kalender in diesem Ausschnitt.";
      } else {
        msg = "Keine Treffer f\u00fcr diesen Filter.";
      }
      var canReset = state.tags.length || state.q;
      el.innerHTML =
        '<p class="events-empty">' + msg + "</p>" +
        (canReset
          ? '<p><button type="button" class="events-empty__reset">\u00d7 filter zur\u00fccksetzen</button></p>'
          : '<p><a href="' + CALENDAR_URL + '" target="_blank" rel="noopener noreferrer">' +
            "Kalender \u00f6ffnen \u2197</a></p>");
      var resetBtn = el.querySelector(".events-empty__reset");
      if (resetBtn) {
        resetBtn.addEventListener("click", function () {
          state.tags = [];
          state.q = "";
          refresh();
        });
      }
      el.removeAttribute("aria-busy");
      return;
    }

    // Group by year-month
    var groups = [];
    var groupMap = {};
    filtered.forEach(function (e) {
      var d = new Date(e.date + "T00:00:00");
      var k = d.getFullYear() + "-" + pad(d.getMonth() + 1);
      if (!groupMap[k]) { groupMap[k] = []; groups.push(k); }
      groupMap[k].push(e);
    });

    var html = "";
    var now = new Date();
    var currentKey = now.getFullYear() + "-" + pad(now.getMonth() + 1);
    groups.forEach(function (k, idx) {
      var parts = k.split("-");
      var monthName = MONTHS_FULL[+parts[1] - 1];
      var isOpen = (k === currentKey || idx === 0) ? " open" : "";
      html += '<details class="events-month"' + isOpen + '>';
      html +=
        '<summary class="events-month__label">' +
        '<span class="events-month__title">[ ' + monthName + " " + parts[0] +
        " ]</span>" +
        '<span class="events-month__chevron" aria-hidden="true"></span>' +
        "</summary>";

      groupMap[k].forEach(function (e) {
        var d = new Date(e.date + "T00:00:00");
        var typeClass = e.type ? " event-card--" + e.type : "";
        // Shared with the RSS feed's deep-link (ics-core.js) so anchors stay in sync.
        var anchor = ICSCore.eventAnchor(e);

        html += '<article class="event-card' + typeClass +
          '" id="' + anchor + '">';

        // Date column
        html += '<div class="event-card__date">';
        html += '<span class="event-card__day">' + pad(d.getDate()) + "</span>";
        html += '<span class="event-card__month">' + MONTHS[d.getMonth()] + "</span>";
        html += '<span class="event-card__dow">' + DAYS[d.getDay()] + "</span>";
        html += "</div>";

        // Content column
        html += '<div class="event-card__content">';
        html += '<div class="event-card__header">';
        html += '<h3 class="event-card__title">' + esc(e.title) + "</h3>";
        if (e.source && e.source !== "bitcircus101") {
          html += '<span class="event-card__source">' +
            esc("Externer Kalender: " + e.source) + "</span>";
        }
        html += "</div>";
        if (e.subtitle) {
          html += '<p class="event-card__subtitle">' + esc(e.subtitle) + "</p>";
        }
        if (e.description) {
          html += '<p class="event-card__desc">' + esc(e.description) + "</p>";
        }
        if (e.location) {
          var osmLoc = encodeURIComponent(e.location);
          html += '<a class="event-card__location" href="' +
            'https://www.openstreetmap.org/search?query=' + osmLoc +
            '" target="_blank" rel="noopener noreferrer" title="Auf Karte anzeigen">' +
            '\u25cb ' + esc(e.location) + "</a>";
        }
        // Meta: time + tags
        html += '<div class="event-card__meta">';
        if (e.time) {
          html += '<span class="event-card__time">' + esc(e.time) + "</span>";
        }
        if (e.tags && e.tags.length) {
          html += '<span class="event-card__tags">';
          e.tags.forEach(function (t) {
            html += '<span class="event-tag">' + esc(t) + "</span>";
          });
          html += "</span>";
        }
        html += "</div>";
        // Action pills
        // External event URLs (e.g. Kult 41) link directly; Nextcloud calendar URLs
        // get the timeGridDay suffix for day view
        var calHref = e.eventUrl
          ? httpUrl(e.eventUrl)
          : httpUrl(e.calendarUrl || CALENDAR_URL) + '/timeGridDay/' + e.date;
        var calLabel = e.eventUrl ? '\u2192 link' : '\u2192 kalender';
        var calTitle = e.eventUrl ? 'Auf externer Seite \u00f6ffnen' : 'Im Kalender anzeigen';
        html += '<div class="event-card__actions">';
        html += '<button class="event-action event-action--link" ' +
          'data-href="#' + anchor + '" title="Link kopieren">' +
          '\u2190 link</button>';
        html += '<a class="event-action event-action--cal" href="' +
          esc(calHref) +
          '" target="_blank" rel="noopener noreferrer" title="' + calTitle + '">' +
          calLabel + '</a>';
        if (e.location) {
          var osmQuery = encodeURIComponent(e.location);
          html += '<a class="event-action event-action--map" href="' +
            'https://www.openstreetmap.org/search?query=' + osmQuery +
            '" target="_blank" rel="noopener noreferrer" title="Auf Karte anzeigen">' +
            '\u25cb karte</a>';
        }
        html += "</div>";
        html += "</div>"; // content
        html += "</article>";
      });

      html += "</details>";
    });

    el.innerHTML = html;
    el.removeAttribute("aria-busy");

    // Permalink: copy URL to clipboard on click. Deliberately asymmetric: the
    // clipboard gets a clean, query-free event permalink (anchor-wins makes it
    // always land), while the address bar keeps the current filter query.
    el.querySelectorAll(".event-action--link").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.preventDefault();
        var href = btn.getAttribute("data-href");
        var url = window.location.origin + window.location.pathname + href;
        window.history.replaceState(null, "", href);
        if (!navigator.clipboard || !navigator.clipboard.writeText) return;
        navigator.clipboard.writeText(url).then(function () {
          var orig = btn.innerHTML;
          btn.innerHTML = '<span class="event-action__icon">\u2713</span> kopiert';
          btn.classList.add("event-action--copied");
          setTimeout(function () {
            btn.innerHTML = orig;
            btn.classList.remove("event-action--copied");
          }, 1500);
        }).catch(function () {
          // Clipboard denied (e.g. non-secure context) \u2014 fail silently, URL is in the bar.
        });
      });
    });

    // Scroll to anchor if URL has hash
    if (window.location.hash) {
      var target = document.getElementById(window.location.hash.slice(1));
      if (target) target.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }

  // ── ICS fallback ──────────────────────────────────────────────────────────
  // The parser lives in ics-core.js (window.ICSCore) and the card shaping in
  // events-core.js (window.EventsCore), both shared with the Node sync script —
  // the fallback renders the same cards (tags, type, truncation) as the JSON path.

  // Source descriptor for the fallback: only the primary Nextcloud calendar is
  // reachable from the browser, so cards carry the same source name the sync uses.
  var FALLBACK_CAL = { id: "bitcircus", name: "bitcircus101", url: CALENDAR_URL, cap: 30 };

  // ── Subscribe box follows the filter ("Filter = Feed") ───────────────────
  // The sync publishes per-tag/per-source feeds and lists them in the `feeds`
  // manifest of events-data.json. With exactly one scope active, the subscribe
  // buttons point at the matching feed; in every other case (no manifest, no
  // match, multi-tag, search active) they keep their shipped targets — never
  // advertise a feed the manifest does not list.

  function snapshotFeedDefaults() {
    if (feedDefaults) return;
    feedDefaults = {};
    var btns = document.querySelectorAll("[data-feed]");
    for (var i = 0; i < btns.length; i++) {
      var b = btns[i];
      feedDefaults[b.getAttribute("data-feed")] = {
        href: b.getAttribute("href"),
        download: b.getAttribute("download"),
      };
    }
  }

  // Exactly one scope, or none: one tag (and nothing else) → that tag's feed;
  // the source toggle alone → the bitcircus source feed.
  function feedScope() {
    if (!feeds || state.q) return null;
    if (state.tags.length === 1 && !state.onlyBitcircus) {
      var key = state.tags[0].toLowerCase(); // manifest tag keys are lowercased
      var entry = feeds.tags && feeds.tags[key];
      return entry ? { entry: entry, label: key } : null;
    }
    if (state.onlyBitcircus && !state.tags.length) {
      // Manifest sources are keyed by cal.id — resolve via the card-facing name.
      var sources = feeds.sources || {};
      for (var id in sources) {
        if (sources[id].name === "bitcircus101") {
          return { entry: sources[id], label: "nur bitcircus101" };
        }
      }
    }
    return null;
  }

  // Several tags at once have no feed of their own — a static site cannot
  // combine them on demand, and pre-building every combination is not a thing.
  // Rather than let the buttons quietly hand out the unfiltered feed, list the
  // per-tag feeds the manifest does have. Only for a pure multi-tag filter:
  // with the source toggle or a search on top, a tag feed would be wider than
  // what the page shows, and advertising it would be a lie.
  function splitScopes() {
    if (!feeds || state.q || state.onlyBitcircus) return null;
    if (state.tags.length < 2) return null;
    var out = [];
    for (var i = 0; i < state.tags.length; i++) {
      var key = state.tags[i].toLowerCase();
      var entry = feeds.tags && feeds.tags[key];
      if (entry && entry.rss) out.push({ tag: key, rss: entry.rss });
    }
    return out.length ? out : null;
  }

  function updateFeedSplit() {
    var box = document.getElementById("events-feed-split");
    if (!box) return;
    var list = box.querySelector(".events-subscribe__scope-links");
    var scopes = splitScopes();
    if (!scopes) {
      box.hidden = true;
      return;
    }
    while (list.firstChild) list.removeChild(list.firstChild);
    for (var i = 0; i < scopes.length; i++) {
      if (i) list.appendChild(document.createTextNode(" · "));
      var a = document.createElement("a");
      a.setAttribute("href", new URL(scopes[i].rss, window.location.href).pathname);
      a.textContent = scopes[i].tag;
      list.appendChild(a);
    }
    box.hidden = false;
  }

  function updateFeedScope() {
    var btns = document.querySelectorAll("[data-feed]");
    if (!btns.length) return;
    snapshotFeedDefaults();

    var scope = feedScope();
    for (var i = 0; i < btns.length; i++) {
      var b = btns[i];
      var kind = b.getAttribute("data-feed"); // webcal | ics | rss
      var def = feedDefaults[kind] || {};
      var path = scope && scope.entry && (kind === "rss" ? scope.entry.rss : scope.entry.ics);
      if (path) {
        // Manifest paths are root-absolute; resolve against the current origin
        // so /events and /events.html behave identically.
        var abs = new URL(path, window.location.href);
        b.setAttribute("href", kind === "webcal" ? "webcal://" + abs.host + abs.pathname : abs.pathname);
        if (kind === "ics") {
          b.setAttribute("download", "bitcircus101-" + path.split("/").pop());
        }
      } else {
        if (def.href) b.setAttribute("href", def.href);
        if (kind === "ics") {
          if (def.download) b.setAttribute("download", def.download);
          else b.removeAttribute("download");
        }
      }
    }

    var note = document.getElementById("events-feed-scope");
    if (note) {
      if (scope) {
        note.querySelector(".events-subscribe__scope-tag").textContent = scope.label;
        note.hidden = false;
      } else {
        note.hidden = true;
      }
    }

    updateFeedSplit();
  }

  // ── Error / Loading ─────────────────────────────────────────────────────

  function renderError(el) {
    el.innerHTML =
      '<div class="events-fallback">' +
      '<p class="events-fallback__cmd">' +
      "termine laden: " +
      '<span class="events-fallback__err">fehlgeschlagen</span></p>' +
      "<p>Termine direkt ansehen: " +
      '<a href="' + CALENDAR_URL + '" target="_blank" rel="noopener noreferrer">' +
      "Kalender \u00f6ffnen \u2197</a></p></div>";
    el.removeAttribute("aria-busy");
  }

  // ── Last Sync Display ────────────────────────────────────────────────────

  var SYNC_BAR_FILL = 60;   // minutes until bar is full (2 cycles)
  var SYNC_WARN = 120;      // minutes until "stale" warning (4 cycles)
  var SYNC_OVERDUE = 180;   // minutes until "überfällig" (6 cycles)

  function syncBar(pct) {
    var total = 10;
    var filled = Math.round(pct * total);
    var empty = total - filled;
    var bar = "";
    for (var i = 0; i < filled; i++) bar += "\u2588";
    for (var i = 0; i < empty; i++) bar += "\u2591";
    return "[" + bar + "]";
  }

  function agoText(mins) {
    if (mins < 1) return "jetzt";
    if (mins < 60) return "vor " + mins + " min";
    var h = Math.floor(mins / 60);
    return "vor " + h + " h " + (mins % 60) + " min";
  }

  function diffText(s) {
    if (!s.added && !s.removed) return "keine \u00c4nderungen";
    var parts = [];
    if (s.added) parts.push("+" + s.added + " neu");
    if (s.removed) parts.push("-" + s.removed + " entfernt");
    return parts.join(" \u00b7 ");
  }

  function showLastSync(sources) {
    var el = document.getElementById("events-last-sync");
    if (!el || !sources || !sources.length) return;

    function render() {
      var now = Date.now();
      var html = "";
      for (var i = 0; i < sources.length; i++) {
        var s = sources[i];
        var isOk = s.status === "ok";
        var isStale = s.status === "stale";
        var hasFetch = s.fetchedAt;

        if ((isOk || isStale) && hasFetch) {
          var elapsed = Math.floor((now - new Date(s.fetchedAt).getTime()) / 60000);
          var pct = Math.min(elapsed / SYNC_BAR_FILL, 1);
          var overdue = elapsed > SYNC_OVERDUE;
          var warning = elapsed > SYNC_WARN;
          var stateClass = overdue ? " sync-source--overdue"
            : (warning || isStale) ? " sync-source--stale" : "";

          html += '<span class="sync-source' + stateClass + '">';
          html += '<span class="sync-source__name">' + esc(s.name) + "</span>";

          // Row 1: Sync freshness
          html += '<span class="sync-source__sync">';
          html += '<span class="sync-source__bar">' + syncBar(pct) + "</span> ";
          html += '<span class="sync-source__ago">' + agoText(elapsed) + "</span>";
          if (overdue) {
            html += ' <span class="sync-source__alert">\u26a0 \u00fcberf\u00e4llig</span>';
          } else if (isStale) {
            html += ' <span class="sync-source__alert" title="' +
              esc(s.error || "Fetch fehlgeschlagen") + '">\u26a0 stale</span>';
          }
          html += "</span>";

          // Row 2: Event stats
          html += '<span class="sync-source__events">';
          html += s.events + " bevorstehende Events";
          if (s.past) {
            html += " \u00b7 " + s.past + " stattgefundene Events";
          }
          if (s.added || s.removed) {
            html += ' \u00b7 <span class="sync-source__diff">' + diffText(s) + "</span>";
          }
          html += "</span>";
        } else {
          html += '<span class="sync-source sync-source--offline">';
          html += '<span class="sync-source__name">' + esc(s.name) + "</span>";
          html += '<span class="sync-source__alert">offline' +
            (s.error ? " \u00b7 " + esc(s.error) : "") + '</span>';
        }
        html += "</span>";
      }
      el.innerHTML = html;
    }

    render();
    var intervalId = setInterval(render, 30000);

    // Clean up when navigating away
    document.addEventListener("visibilitychange", function () {
      if (document.hidden) {
        clearInterval(intervalId);
        intervalId = null;
      } else if (!intervalId) {
        render();
        intervalId = setInterval(render, 30000);
      }
    });
  }

  // ── Init ──────────────────────────────────────────────────────────────────

  function init() {
    var el = document.getElementById("events-list");
    if (!el) return;

    // A missing shared module (404, stale cache skew) would otherwise surface as
    // a ReferenceError inside the fetch chain — fail visibly instead.
    if (typeof ICSCore === "undefined" || typeof EventsCore === "undefined") {
      renderError(el);
      return;
    }

    // Read URL state BEFORE the fetch so the very first render already
    // reflects a shared link \u2014 no unfiltered flash.
    parseState();

    el.innerHTML =
      '<p class="events-loading">' +
      '<span class="events-loading__cmd">lade termine</span>' +
      '<span class="events-cursor"> \u2026</span></p>';

    fetch(JSON_URL)
      .then(function (res) {
        if (!res.ok) throw new Error("no json");
        return res.json();
      })
      .then(function (data) {
        // Support both { lastSync, sources, events } wrapper and plain array
        var events = Array.isArray(data) ? data : data.events;
        var sources = Array.isArray(data) ? null : data.sources;
        feeds = (!Array.isArray(data) && data.feeds) || null;
        if (!events || !events.length) throw new Error("empty");
        renderCards(events, el);
        if (sources) showLastSync(sources);
      })
      .catch(function () {
        fetch(ICS_URL, { mode: "cors" })
          .then(function (res) {
            if (!res.ok) throw new Error("HTTP " + res.status);
            return res.text();
          })
          .then(function (text) {
            renderCards(EventsCore.toCards(ICSCore.parseICS(text, "fallback"), FALLBACK_CAL), el);
          })
          .catch(function () {
            renderError(el);
          });
      });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
