/**
 * events.js — bitcircus101 event renderer
 * Loads events from events-data.json (generated by CI),
 * falls back to ICS fetch from Nextcloud.
 */
(function () {
  "use strict";

  var JSON_URL = "events-data.json";
  var ICS_URL =
    "https://nc.6bm.de/remote.php/dav/public-calendars/DCaFSYECrcTJRJjC?export";
  var CALENDAR_URL =
    "https://nc.6bm.de/apps/calendar/p/DCaFSYECrcTJRJjC";
  var MONTHS = [
    "JAN", "FEB", "M\u00c4R", "APR", "MAI", "JUN",
    "JUL", "AUG", "SEP", "OKT", "NOV", "DEZ",
  ];
  var MONTHS_FULL = [
    "JANUAR", "FEBRUAR", "M\u00c4RZ", "APRIL", "MAI", "JUNI",
    "JULI", "AUGUST", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DEZEMBER",
  ];
  var DAYS = ["SO", "MO", "DI", "MI", "DO", "FR", "SA"];
  var HORIZON = 120;

  // State
  var activeFilters = [];
  var allUpcoming = [];
  var allFutureSorted = [];
  var onlyBitcircus = false;
  var eventsContainer = null;
  var filterBar = null;
  var eventsToolbar = null;

  function pad(n) { return n < 10 ? "0" + n : "" + n; }

  function esc(s) {
    return s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  }

  function formatSourceLabel(name) {
    if (name === "Datenburg e.V.") {
      return "Externer Kalender: Datenburg e.V.";
    }
    return name;
  }

  function isBitcircusEvent(e) {
    return !e.source || e.source === "bitcircus101";
  }

  function rebuildDisplayedUpcoming() {
    var pool = onlyBitcircus
      ? allFutureSorted.filter(isBitcircusEvent)
      : allFutureSorted;
    allUpcoming = pool.slice(0, 30);
  }

  function removeFilterBar() {
    if (filterBar && filterBar.parentNode) {
      filterBar.parentNode.removeChild(filterBar);
    }
    filterBar = null;
    activeFilters = [];
  }

  function ensureEventsToolbar(insertBeforeNode) {
    if (eventsToolbar && eventsToolbar.parentNode) return;
    var parent = insertBeforeNode.parentNode;
    eventsToolbar = document.createElement("div");
    eventsToolbar.className = "events-toolbar";
    eventsToolbar.innerHTML =
      '<label class="events-toolbar__label">' +
      '<input type="checkbox" id="events-only-bitcircus" class="events-toolbar__checkbox" />' +
      "<span>Nur Events im bitcircus101 anzeigen</span></label>";
    parent.insertBefore(eventsToolbar, insertBeforeNode);
    document.getElementById("events-only-bitcircus").addEventListener(
      "change",
      function () {
        onlyBitcircus = this.checked;
        removeFilterBar();
        rebuildDisplayedUpcoming();
        buildTagsAndFilter();
      }
    );
  }

  function buildTagsAndFilter() {
    var el = eventsContainer;
    if (!allUpcoming.length) {
      if (onlyBitcircus && allFutureSorted.length) {
        el.innerHTML =
          '<p class="events-empty">Keine bevorstehenden Termine nur im bitcircus101-Kalender in diesem Ausschnitt.</p>' +
          "<p><a href=\"" + CALENDAR_URL + "\" target=\"_blank\" rel=\"noopener\">" +
          "Kalender \u00f6ffnen \u2197</a></p>";
      } else {
        el.innerHTML =
          '<p class="events-empty">Keine kommenden Termine gefunden.</p>' +
          '<p><a href="' + CALENDAR_URL + '" target="_blank" rel="noopener">' +
          "Kalender \u00f6ffnen \u2197</a></p>";
      }
      return;
    }

    var tagSet = {};
    allUpcoming.forEach(function (e) {
      (e.tags || []).forEach(function (t) { tagSet[t] = true; });
    });
    var allTags = Object.keys(tagSet).sort();
    if (allTags.length) {
      buildFilterBar(allTags, el);
    }
    renderFilteredCards();
  }

  // ── Card Renderer ─────────────────────────────────────────────────────────

  function renderCards(events, el) {
    eventsContainer = el;
    var now = new Date();
    now.setHours(0, 0, 0, 0);

    allFutureSorted = events
      .filter(function (e) {
        return new Date(e.date + "T23:59:59") >= now;
      })
      .sort(function (a, b) {
        return new Date(a.date) - new Date(b.date);
      });

    onlyBitcircus = false;
    if (eventsToolbar) {
      var resetCb = document.getElementById("events-only-bitcircus");
      if (resetCb) resetCb.checked = false;
    }

    if (!allFutureSorted.length) {
      if (eventsToolbar && eventsToolbar.parentNode) {
        eventsToolbar.parentNode.removeChild(eventsToolbar);
        eventsToolbar = null;
      }
      removeFilterBar();
      el.innerHTML =
        '<p class="events-empty">Keine kommenden Termine gefunden.</p>' +
        '<p><a href="' + CALENDAR_URL + '" target="_blank" rel="noopener">' +
        "Kalender \u00f6ffnen \u2197</a></p>";
      return;
    }

    ensureEventsToolbar(el);
    rebuildDisplayedUpcoming();
    removeFilterBar();
    buildTagsAndFilter();
  }

  function buildFilterBar(tags, el) {
    if (!tags.length) return;

    filterBar = document.createElement("div");
    filterBar.className = "events-filter";

    var html = '<span class="events-filter__label">$ filter</span>';
    tags.forEach(function (t) {
      html += '<button class="events-filter__tag" data-tag="' +
        esc(t) + '">' + esc(t) + "</button>";
    });
    html += '<button class="events-filter__clear" style="display:none">' +
      "\u00d7 reset</button>";
    filterBar.innerHTML = html;

    el.parentNode.insertBefore(filterBar, el);

    var clearBtn = filterBar.querySelector(".events-filter__clear");
    filterBar.querySelectorAll(".events-filter__tag").forEach(function (btn) {
      btn.addEventListener("click", function () {
        var tag = btn.getAttribute("data-tag");
        var idx = activeFilters.indexOf(tag);
        if (idx > -1) {
          activeFilters.splice(idx, 1);
          btn.classList.remove("active");
        } else {
          activeFilters.push(tag);
          btn.classList.add("active");
        }
        clearBtn.style.display = activeFilters.length ? "" : "none";
        renderFilteredCards();
      });
    });

    clearBtn.addEventListener("click", function () {
      activeFilters = [];
      filterBar.querySelectorAll(".events-filter__tag").forEach(function (b) {
        b.classList.remove("active");
      });
      clearBtn.style.display = "none";
      renderFilteredCards();
    });
  }

  function renderFilteredCards() {
    var el = eventsContainer;
    var filtered = activeFilters.length
      ? allUpcoming.filter(function (e) {
          return activeFilters.some(function (f) {
            return (e.tags || []).indexOf(f) > -1;
          });
        })
      : allUpcoming;

    if (!filtered.length) {
      el.innerHTML =
        '<p class="events-empty">Keine Treffer f\u00fcr diesen Filter.</p>';
      return;
    }

    // Group by year-month
    var groups = [];
    var groupMap = {};
    filtered.forEach(function (e) {
      var d = new Date(e.date + "T00:00:00");
      var k = d.getFullYear() + "-" + pad(d.getMonth() + 1);
      if (!groupMap[k]) { groupMap[k] = []; groups.push(k); }
      groupMap[k].push(e);
    });

    var html = "";
    var now = new Date();
    var currentKey = now.getFullYear() + "-" + pad(now.getMonth() + 1);
    groups.forEach(function (k, idx) {
      var parts = k.split("-");
      var monthName = MONTHS_FULL[+parts[1] - 1];
      var isOpen = (k === currentKey || idx === 0) ? " open" : "";
      html += '<details class="events-month"' + isOpen + '>';
      html +=
        '<summary class="events-month__label">' +
        '<span class="events-month__title">[ ' + monthName + " " + parts[0] +
        " ]</span>" +
        '<span class="events-month__chevron" aria-hidden="true"></span>' +
        "</summary>";

      groupMap[k].forEach(function (e) {
        var d = new Date(e.date + "T00:00:00");
        var typeClass = e.type ? " event-card--" + e.type : "";
        var slug = e.date + "-" + e.title.toLowerCase()
          .replace(/[^a-z0-9\u00e4\u00f6\u00fc]+/g, "-")
          .replace(/^-|-$/g, "").slice(0, 40);
        var anchor = "ev-" + slug;

        html += '<article class="event-card' + typeClass +
          '" id="' + anchor + '">';

        // Date column
        html += '<div class="event-card__date">';
        html += '<span class="event-card__day">' + pad(d.getDate()) + "</span>";
        html += '<span class="event-card__month">' + MONTHS[d.getMonth()] + "</span>";
        html += '<span class="event-card__dow">' + DAYS[d.getDay()] + "</span>";
        html += "</div>";

        // Content column
        html += '<div class="event-card__content">';
        html += '<div class="event-card__header">';
        html += '<h3 class="event-card__title">' + esc(e.title) + "</h3>";
        if (e.source && e.source !== "bitcircus101") {
          html += '<span class="event-card__source">' +
            esc(formatSourceLabel(e.source)) + "</span>";
        }
        html += "</div>";
        if (e.subtitle) {
          html += '<p class="event-card__subtitle">' + esc(e.subtitle) + "</p>";
        }
        if (e.description) {
          html += '<p class="event-card__desc">' + esc(e.description) + "</p>";
        }
        if (e.location) {
          html += '<p class="event-card__location">' +
            '\u25cb ' + esc(e.location) + "</p>";
        }
        // Meta: time + tags
        html += '<div class="event-card__meta">';
        if (e.time) {
          html += '<span class="event-card__time">' + esc(e.time) + "</span>";
        }
        if (e.tags && e.tags.length) {
          html += '<span class="event-card__tags">';
          e.tags.forEach(function (t) {
            html += '<span class="event-tag">' + esc(t) + "</span>";
          });
          html += "</span>";
        }
        html += "</div>";
        // Action pills
        var calUrl = e.calendarUrl || CALENDAR_URL;
        html += '<div class="event-card__actions">';
        html += '<button class="event-action event-action--link" ' +
          'data-href="#' + anchor + '" title="Link kopieren">' +
          '\u2190 link</button>';
        html += '<a class="event-action event-action--cal" href="' +
          calUrl + '/timeGridDay/' + e.date +
          '" target="_blank" rel="noopener" title="Im Kalender anzeigen">' +
          '\u2192 kalender</a>';
        if (e.location) {
          var osmQuery = encodeURIComponent(e.location);
          html += '<a class="event-action event-action--map" href="' +
            'https://www.openstreetmap.org/search?query=' + osmQuery +
            '" target="_blank" rel="noopener" title="Auf Karte anzeigen">' +
            '\u25cb karte</a>';
        }
        html += "</div>";
        html += "</div>"; // content
        html += "</article>";
      });

      html += "</details>";
    });

    el.innerHTML = html;

    // Permalink: copy URL to clipboard on click
    el.querySelectorAll(".event-action--link").forEach(function (btn) {
      btn.addEventListener("click", function (e) {
        e.preventDefault();
        var href = btn.getAttribute("data-href");
        var url = window.location.origin + window.location.pathname + href;
        window.history.replaceState(null, "", href);
        navigator.clipboard.writeText(url).then(function () {
          var orig = btn.innerHTML;
          btn.innerHTML = '<span class="event-action__icon">\u2713</span> kopiert';
          btn.classList.add("event-action--copied");
          setTimeout(function () {
            btn.innerHTML = orig;
            btn.classList.remove("event-action--copied");
          }, 1500);
        });
      });
    });

    // Scroll to anchor if URL has hash
    if (window.location.hash) {
      var target = document.getElementById(window.location.hash.slice(1));
      if (target) target.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }

  // ── ICS Parser (fallback) ─────────────────────────────────────────────────

  function icsDate(v) {
    if (!v) return null;
    var y = +v.slice(0, 4), m = +v.slice(4, 6) - 1, d = +v.slice(6, 8);
    if (v.length === 8) return new Date(y, m, d);
    var h = +v.slice(9, 11), mi = +v.slice(11, 13);
    return v.charAt(v.length - 1) === "Z"
      ? new Date(Date.UTC(y, m, d, h, mi))
      : new Date(y, m, d, h, mi);
  }

  function nthWeekday(year, month, wd, nth) {
    var d = new Date(year, month, 1);
    while (d.getDay() !== wd) d.setDate(d.getDate() + 1);
    d.setDate(d.getDate() + (nth - 1) * 7);
    return d.getMonth() === month ? d : null;
  }

  function expandRRule(dtstart, rule, exdates) {
    var horizon = new Date();
    horizon.setDate(horizon.getDate() + HORIZON);
    var p = {};
    rule.split(";").forEach(function (s) {
      var i = s.indexOf("=");
      if (i > -1) p[s.slice(0, i)] = s.slice(i + 1);
    });
    var WD = { SU: 0, MO: 1, TU: 2, WE: 3, TH: 4, FR: 5, SA: 6 };
    var end = p.UNTIL ? icsDate(p.UNTIL) : null;
    if (!end || end > horizon) end = horizon;
    var max = p.COUNT ? +p.COUNT : 200;
    var exSet = {};
    exdates.forEach(function (d) { exSet[d.toDateString()] = true; });
    var out = [];

    if (p.FREQ === "WEEKLY") {
      var wd = p.BYDAY
        ? WD[p.BYDAY.replace(/\d/g, "").slice(-2)]
        : dtstart.getDay();
      if (wd === undefined) wd = dtstart.getDay();
      var cur = new Date(dtstart);
      while (cur.getDay() !== wd) cur.setDate(cur.getDate() + 1);
      while (cur <= end && out.length < max) {
        if (!exSet[cur.toDateString()]) out.push(new Date(cur));
        cur.setDate(cur.getDate() + 7);
      }
    } else if (p.FREQ === "MONTHLY" && p.BYDAY) {
      // Support both "3TH" (nth in BYDAY) and "TH" + BYSETPOS=3
      var m = p.BYDAY.match(/^(\d+)([A-Z]{2})$/);
      var nth = m ? +m[1] : (p.BYSETPOS ? +p.BYSETPOS : null);
      var dayCode = m ? m[2] : p.BYDAY.replace(/\d/g, "").slice(-2);
      var twd = WD[dayCode];
      if (nth && twd != null) {
        var mo = new Date(dtstart.getFullYear(), dtstart.getMonth(), 1);
        while (mo <= end && out.length < max) {
          var d = nthWeekday(mo.getFullYear(), mo.getMonth(), twd, nth);
          if (d) {
            d.setHours(dtstart.getHours(), dtstart.getMinutes(), 0, 0);
            if (d >= dtstart && d <= end && !exSet[d.toDateString()])
              out.push(new Date(d));
          }
          mo.setMonth(mo.getMonth() + 1);
        }
      }
    }
    return out;
  }

  function cleanICS(s) {
    return s.replace(/\\n/gi, " ").replace(/\\,/g, ",").replace(/\\;/g, ";").trim();
  }

  function parseICS(text) {
    var lines = text.replace(/\r?\n[ \t]/g, "").split(/\r?\n/);
    var events = [];
    var ev = null;

    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      if (line === "BEGIN:VEVENT") { ev = { exdates: [] }; continue; }
      if (line === "END:VEVENT") {
        if (!ev || !ev.dtstart) { ev = null; continue; }
        var dtstart = icsDate(ev.dtstart);
        if (!dtstart) { ev = null; continue; }
        var dtend = ev.dtend ? icsDate(ev.dtend) : null;
        var allDay = !ev.dtstart.includes("T");
        var base = {
          summary: cleanICS(ev.summary || "(kein Titel)"),
          description: cleanICS(ev.description || ""),
          location: cleanICS(ev.location || ""),
          allDay: allDay,
        };
        if (ev.rrule) {
          var dur = dtend ? dtend - dtstart : 7200000;
          expandRRule(dtstart, ev.rrule, ev.exdates).forEach(function (d) {
            events.push({
              summary: base.summary, description: base.description,
              location: base.location, allDay: base.allDay,
              dtstart: d, dtend: new Date(d.getTime() + dur),
            });
          });
        } else {
          base.dtstart = dtstart;
          base.dtend = dtend;
          events.push(base);
        }
        ev = null; continue;
      }
      if (!ev) continue;
      var ci = line.indexOf(":");
      if (ci === -1) continue;
      var key = line.slice(0, ci).split(";")[0].toUpperCase();
      var val = line.slice(ci + 1);
      if (key === "DTSTART") ev.dtstart = val;
      else if (key === "DTEND") ev.dtend = val;
      else if (key === "SUMMARY") ev.summary = val;
      else if (key === "DESCRIPTION") ev.description = val;
      else if (key === "LOCATION") ev.location = val;
      else if (key === "RRULE") ev.rrule = val;
      else if (key === "EXDATE") {
        val.split(",").forEach(function (v) {
          var d = icsDate(v.trim());
          if (d) ev.exdates.push(d);
        });
      }
    }
    return events;
  }

  function icsToCards(icsEvents) {
    var now = new Date();
    return icsEvents
      .filter(function (e) { return e.dtstart > now; })
      .sort(function (a, b) { return a.dtstart - b.dtstart; })
      .slice(0, 30)
      .map(function (e) {
        return {
          title: e.summary,
          subtitle: "",
          description: e.description,
          date: e.dtstart.toISOString().slice(0, 10),
          time: e.allDay
            ? ""
            : pad(e.dtstart.getHours()) + ":" + pad(e.dtstart.getMinutes()),
          tags: [],
          type: "regular",
        };
      });
  }

  // ── Error / Loading ─────────────────────────────────────────────────────

  function renderError(el) {
    el.innerHTML =
      '<div class="events-fallback">' +
      '<p class="events-fallback__cmd">' +
      "$ events --load " +
      '<span class="events-fallback__err">ERR</span></p>' +
      "<p>Termine direkt ansehen: " +
      '<a href="' + CALENDAR_URL + '" target="_blank" rel="noopener">' +
      "Kalender \u00f6ffnen \u2197</a></p></div>";
  }

  // ── Last Sync Display ────────────────────────────────────────────────────

  function fmtDate(isoStr) {
    var d = new Date(isoStr);
    return pad(d.getDate()) + "." + pad(d.getMonth() + 1) + "." +
      d.getFullYear() + " " + pad(d.getHours()) + ":" + pad(d.getMinutes());
  }

  var SYNC_BAR_FILL = 60;   // minutes until bar is full (2 cycles)
  var SYNC_WARN = 120;      // minutes until "stale" warning (4 cycles)
  var SYNC_OVERDUE = 180;   // minutes until "überfällig" (6 cycles)

  function syncBar(pct) {
    var total = 10;
    var filled = Math.round(pct * total);
    var empty = total - filled;
    var bar = "";
    for (var i = 0; i < filled; i++) bar += "\u2588";
    for (var i = 0; i < empty; i++) bar += "\u2591";
    return "[" + bar + "]";
  }

  function agoText(mins) {
    if (mins < 1) return "jetzt";
    if (mins < 60) return "vor " + mins + " min";
    var h = Math.floor(mins / 60);
    return "vor " + h + " h " + (mins % 60) + " min";
  }

  function diffText(s) {
    if (!s.added && !s.removed) return "keine \u00c4nderungen";
    var parts = [];
    if (s.added) parts.push("+" + s.added + " neu");
    if (s.removed) parts.push("-" + s.removed + " entfernt");
    return parts.join(" \u00b7 ");
  }

  function showLastSync(sources) {
    var el = document.getElementById("events-last-sync");
    if (!el || !sources || !sources.length) return;

    function render() {
      var now = Date.now();
      var html = "";
      for (var i = 0; i < sources.length; i++) {
        var s = sources[i];
        var isOk = s.status === "ok";
        var isStale = s.status === "stale";
        var hasFetch = s.fetchedAt;

        if ((isOk || isStale) && hasFetch) {
          var elapsed = Math.floor((now - new Date(s.fetchedAt).getTime()) / 60000);
          var pct = Math.min(elapsed / SYNC_BAR_FILL, 1);
          var overdue = elapsed > SYNC_OVERDUE;
          var warning = elapsed > SYNC_WARN;
          var stateClass = overdue ? " sync-source--overdue"
            : (warning || isStale) ? " sync-source--stale" : "";

          html += '<span class="sync-source' + stateClass + '">';
          html += '<span class="sync-source__name">' + esc(s.name) + "</span>";

          // Row 1: Sync freshness
          html += '<span class="sync-source__sync">';
          html += '<span class="sync-source__bar">' + syncBar(pct) + "</span> ";
          html += '<span class="sync-source__ago">' + agoText(elapsed) + "</span>";
          if (overdue) {
            html += ' <span class="sync-source__alert">\u26a0 \u00fcberf\u00e4llig</span>';
          } else if (isStale) {
            html += ' <span class="sync-source__alert" title="' +
              esc(s.error || "Fetch fehlgeschlagen") + '">\u26a0 stale</span>';
          }
          html += "</span>";

          // Row 2: Event stats
          html += '<span class="sync-source__events">';
          html += s.events + " bevorstehende Events";
          if (s.past) {
            html += " \u00b7 " + s.past + " stattgefundene Events";
          }
          if (s.added || s.removed) {
            html += ' \u00b7 <span class="sync-source__diff">' + diffText(s) + "</span>";
          }
          html += "</span>";
        } else {
          html += '<span class="sync-source sync-source--offline">';
          html += '<span class="sync-source__name">' + esc(s.name) + "</span>";
          html += '<span class="sync-source__alert">offline' +
            (s.error ? " \u00b7 " + esc(s.error) : "") + '</span>';
        }
        html += "</span>";
      }
      el.innerHTML = html;
    }

    render();
    var intervalId = setInterval(render, 30000);

    // Clean up when navigating away
    document.addEventListener("visibilitychange", function () {
      if (document.hidden) {
        clearInterval(intervalId);
        intervalId = null;
      } else if (!intervalId) {
        render();
        intervalId = setInterval(render, 30000);
      }
    });
  }

  // ── Init ──────────────────────────────────────────────────────────────────

  function init() {
    var el = document.getElementById("events-list");
    if (!el) return;

    el.innerHTML =
      '<p class="events-loading">' +
      '<span class="events-loading__cmd">$ events --load</span>' +
      '<span class="events-cursor">\u258b</span></p>';

    fetch(JSON_URL)
      .then(function (res) {
        if (!res.ok) throw new Error("no json");
        return res.json();
      })
      .then(function (data) {
        // Support both { lastSync, sources, events } wrapper and plain array
        var events = Array.isArray(data) ? data : data.events;
        var sources = Array.isArray(data) ? null : data.sources;
        if (!events || !events.length) throw new Error("empty");
        renderCards(events, el);
        if (sources) showLastSync(sources);
      })
      .catch(function () {
        fetch(ICS_URL, { mode: "cors" })
          .then(function (res) {
            if (!res.ok) throw new Error("HTTP " + res.status);
            return res.text();
          })
          .then(function (text) {
            renderCards(icsToCards(parseICS(text)), el);
          })
          .catch(function () {
            renderError(el);
          });
      });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
