name: Generate sitemap

permissions:
  contents: write # Push-Recht für github-actions[bot]

on:
  push:
    branches: [live] # oder [ main ] – je nach Setup
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # korrekte <lastmod>-Daten
          persist-credentials: true

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1.10.1 # feste Version empfohlen
        id: sitemap
        with:
          base-url-path: https://bitcircus101.de # ← deine Domain
          path-to-root: . # (Standard, kann entfallen)
          include-html: true
          include-pdf: true # Standardwerte, nur zur Klarheit
          sitemap-format: xml # "

      - name: Commit sitemap
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git diff --cached --quiet && echo "No changes" || git commit -m "Update sitemap"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
